/*
Copyright (c) 2014, RMIT Training
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of CounterCompliance nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 

using System;
using System.Collections.Generic;
using System.ServiceModel;
using System.Xml.Serialization;

#pragma warning disable 1591 //disables XML documentation warnings

namespace RMIT.Counter.Libraries.Sushi.Core
{
   /// <remarks/>
   [SerializableAttribute()]
   [XmlTypeAttribute(Namespace = "http://www.niso.org/schemas/sushi")]
   public partial class ReportRequest
   {
       /// <remarks/>
       [XmlElement(Order = 0)]
       public Requestor Requestor { get; set; }

       /// <remarks/>
       [XmlElement(Order = 1)]
       public CustomerReference CustomerReference { get; set; }

       /// <remarks/>
       [XmlElement(Order = 2)]
       public ReportDefinition ReportDefinition { get; set; }

       /// <remarks/>
       [XmlAttribute()]
       public DateTime Created { get; set; }

       /// <remarks/>
       [XmlIgnore()]
       public bool CreatedSpecified { get; set; }

       /// <remarks/>
       [XmlAttribute()]
       public string ID { get; set; }
   }

   /// <remarks/>

   [SerializableAttribute()]
   [XmlTypeAttribute(Namespace = "http://www.niso.org/schemas/sushi")]
   public partial class Requestor
   {
       /// <remarks/>
       [XmlElement(Order = 0)]
       public string ID { get; set; }

       /// <remarks/>
       [XmlElement(Order = 1)]
       public string Name { get; set; }

       /// <remarks/>
       [XmlElement(Order = 2)]
       public string Email { get; set; }
   }

   [SerializableAttribute()]
   [XmlTypeAttribute(Namespace = "http://www.niso.org/schemas/sushi")]
   public partial class Activity
   {
   }

   /// <remarks/>

   [SerializableAttribute()]
   [XmlTypeAttribute(Namespace = "http://www.niso.org/schemas/sushi")]
   public partial class Exception
   {
       /// <remarks/>
       [XmlElement(Order = 0)]
       public int Number { get; set; }

       /// <remarks/>
       [XmlElement(Order = 1)]
       public ExceptionSeverity Severity { get; set; }

       /// <remarks/>
       [XmlElement(Order = 2)]
       public string Message { get; set; }

       /// <remarks/>
       [XmlElement(DataType = "anyURI", IsNullable = true, Order = 3)]
       public string HelpUrl { get; set; }

       /// <remarks/>
       [XmlElement(IsNullable = true, Order = 4)]
       public object Data { get; set; }

       /// <remarks/>
       [XmlAttribute()]
       public DateTime Created { get; set; }

       /// <remarks/>
       [XmlIgnore()]
       public bool CreatedSpecified { get; set; }
   }

   /// <remarks/>

   [SerializableAttribute()]
   [XmlTypeAttribute(Namespace = "http://www.niso.org/schemas/sushi")]
   public enum ExceptionSeverity
   {

      /// <remarks/>
      Info,

      /// <remarks/>
      Debug,

      /// <remarks/>
      Warning,

      /// <remarks/>
      Error,

      /// <remarks/>
      Fatal,
   }

   /// <remarks/>
   //[XmlIncludeAttribute(typeof(CounterReportResponse))]
   [SerializableAttribute()]
   [XmlTypeAttribute(Namespace = "http://www.niso.org/schemas/sushi")]
   public partial class ReportResponse
   {
       /// <remarks/>
       [XmlElement("Exception", IsNullable = true, Order = 0)]
       public Exception[] Exception { get; set; }

       /// <remarks/>
       [XmlElement(Order = 1)]
       public Requestor Requestor { get; set; }

       /// <remarks/>
       [XmlElement(Order = 2)]
       public CustomerReference CustomerReference { get; set; }

       /// <remarks/>
       [XmlElement(Order = 3)]
       public ReportDefinition ReportDefinition { get; set; }

       /// <remarks/>
       [XmlAttribute()]
       public DateTime Created { get; set; }

       /// <remarks/>
       [XmlIgnore()]
       public bool CreatedSpecified { get; set; }

       /// <remarks/>
       [XmlAttribute()]
       public string ID { get; set; }
   }

   /// <remarks/>

   [SerializableAttribute()]
   [XmlTypeAttribute(Namespace = "http://www.niso.org/schemas/sushi")]
   public partial class CustomerReference
   {
       /// <remarks/>
       [XmlElement(Order = 0)]
       public string ID { get; set; }

       /// <remarks/>
       [XmlElement(IsNullable = true, Order = 1)]
       public string Name { get; set; }
   }

   /// <remarks/>

   [SerializableAttribute()]
   [XmlTypeAttribute(Namespace = "http://www.niso.org/schemas/sushi")]
   public partial class ReportDefinition
   {
       /// <remarks/>
       [XmlElement(Order = 0)]
       public ReportDefinitionFilters Filters { get; set; }

       /// <remarks/>
       [XmlAttribute()]
       public string Name { get; set; }

       /// <remarks/>
       [XmlAttribute()]
       public string Release { get; set; }
   }

   /// <remarks/>

   [SerializableAttribute()]
   [XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.niso.org/schemas/sushi")]
   public partial class ReportDefinitionFilters
   {
       /// <remarks/>
       [XmlElementAttribute(Order = 0)]
       public Range UsageDateRange { get; set; }
   }

   /// <remarks/>

   [SerializableAttribute()]
   [XmlType(Namespace = "http://www.niso.org/schemas/sushi")]
   public partial class Range
   {
       /// <remarks/>
       [XmlElement(DataType = "date", Order = 0)]
       public DateTime Begin { get; set; }

       /// <remarks/>
       [XmlElement(DataType = "date", Order = 1)]
       public DateTime End { get; set; }
   }

   [MessageContract(IsWrapped = false)]
   public partial class GetReportRequest
   {

      [MessageBodyMember(Namespace = "http://www.niso.org/schemas/sushi/counter", Order = 0)]
      public ReportRequest ReportRequest;

      public GetReportRequest()
      {
      }

      public GetReportRequest(ReportRequest ReportRequest)
      {
         this.ReportRequest = ReportRequest;
      }
   }

   [MessageContractAttribute(IsWrapped = false)]
   public partial class GetReportResponse
   {

      [MessageBodyMemberAttribute(Namespace = "http://www.niso.org/schemas/sushi/counter", Order = 0)]
      public CounterReportResponse ReportResponse;

      public GetReportResponse()
      {
      }

      public GetReportResponse(CounterReportResponse ReportResponse)
      {
         this.ReportResponse = ReportResponse;
      }
   }
   [SerializableAttribute()]
   [XmlTypeAttribute(Namespace = "http://www.niso.org/schemas/sushi/counter")]
   public partial class CounterReportResponse : ReportResponse
   {
       /// <remarks/>
       [XmlArrayAttribute(IsNullable = true, Order = 0), XmlArrayItemAttribute(Namespace = "http://www.niso.org/schemas/counter", IsNullable = false)]
       public List<Report> Report { get; set; }
   }
}